In [1]:
import json

In [2]:
with open("data/train.jsonl") as f:
    data = [json.loads(line) for line in f]

In [3]:
from latain.core import Block

In [17]:
block = Block.from_dict(data[4])

In [18]:
block_text = ""
for line in block:
    line_text = ""
    for span in line:
        line_text += span.text + "\t"
    block_text += line_text + "\n"
print(block_text)

目前职位概况	
公司名称:	北京蓝色光标品牌管理顾问股份有限公司	
所任职位:	会计	
所在行业:	广告/公关/巿场推广/会展	
工作地点:	北京	
目前年薪:	保密	
工作经历	
2016.03 -至今	北京蓝色光标品牌管理顾问股份有限公司	
会计	
-所在地区:北京	
-下属人数:1人	
-职责业绩:	
1.统筹公司资金,为管理层出具资金报表o分析资金流动,预计现金流情况o	
2.负责所属税务申报,汇算清缴,跟进最新税务政策;同时负责工商变更,注销,统计年	
报等工作o	
3.审核合同,及应收/应付/费用账务处理o	
4.核对应收,应付,费用的全部工作,安排财务结账时间;同时完成业财一致相关工作	
(OA,oracle,HFM)	
5出具(更新)财务报销各项费用具体制度,完成制度的演讲o	
6.统计应收欠款,为各个业务组催款做准备o	
7.对公司日常经营业务,从财务角度为业务人员提出意见和支持,提供最优的选择o	
8.配合各个部内及领导层制定各部内预算o	
9.出具法人报表,合并报表,核对关联交易,提供费用预算,配合审计工作o	
2015.03 -	云南沃林普顿药业有限公司	
2016.02	
会计	
-所在地区:昆明	
-下属人数:0人	
-职责业绩:	
1.主要是用用友erp软件负责与供应商的往来核算,完成凭证录入o	
2.组织仓库盘点工作,完成盘库情况报告o	
3.每月根据公司的出入库情况来编往来款明细帐,与供应商和客户进行核对o	
4.每月完成与相关公司的对账与开票o	
5.审核原始单据,填制记帐凭证,登记明细帐和总帐o	
6.利用Excel完成月底各相关报表与分析o	
7.按照国家有关现金管理和银行结算制度的规定,办理现金收付业务和银行结算业务o	
8.购买,保管,开具增值税专用发票和普通发票o	
9.登记现金账和银行账,编制银行余额调节表,做到账证相符,账账相符,日清月结o	
10.管理公司的支票,电汇,银行承兑汇票等等票据o	
11.负责账目和凭证的装订和保管o	



In [10]:
import torch
import torch.nn as nn
from torch import Tensor


class CommLayer(nn.Module):

    def __init__(self, hidden_size: int):
        super().__init__()
        #self.linear = nn.Linear(hidden_size, hidden_size)
        # self.dropout = nn.Dropout(dropout)
        # self.layerNorm = nn.LayerNorm(hidden_size)

    def forward(self, hidden_states: Tensor, comm_matrix: Tensor) -> Tensor:
        # hidden_states: (batch_size, num_item, hidden_size)
        # comm_matrix: (batch_size, num_item, num_item)
        # X: (batch_size, num_item, hidden_size)
        #X = self.linear(hidden_states)
        X = hidden_states
        # 
        X = torch.bmm(comm_matrix, X)
        X = hidden_states + X
        return X


/home/www/miniconda3/envs/simpletrainer/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
cl = CommLayer(3)

In [12]:
h = torch.randn(1, 2, 3)
c = torch.tensor([[.2, .8], [.3, .7]]).unsqueeze(0)

In [13]:
cl(h, c)

tensor([[[ 2.3166, -1.7714, -1.8924],
         [ 1.9441, -2.8346, -0.2883]]])

In [14]:
h[0, 0, :] * 0.2 + h[0, 1, :] * 0.8 + h[0,0,:]

tensor([ 2.3166, -1.7714, -1.8924])

In [15]:
h.squeeze(0)

tensor([[ 1.3238, -0.4131, -1.6592],
        [ 0.9100, -1.5945,  0.1232]])

In [16]:
for line in block:
    for span in line:
        print(span.tag)













company|timeRange
title




















company|timeRange
title













company|timeRange
title























